f=open("abcdef.txt",'w')
print("File Name: ",f.name)
print("File Mode: ",f.mode)
print("Is File Readable: ",f.readable())
print("Is File Writable: ",f.writable())
print("Is File Closed : ",f.closed)
f.close()
print("Is File Closed : ",f.closed)

f=open("abc.txt","w+")
print("file name: ",f.name)
print("file mode: ", f.mode)
print("Is file readable: ",f.readable())
print("Is file writable: ",f.writable())
print("Is file closed: ", f.closed)
f.close()
print("Is file closed: ",f.closed )

